### ISSUE TITLE
"System.Private.CoreLib: Exception while executing function: SendSmsTimer. SendSmsTimer: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' "

### ISSUE THREAD

**Issue by sinisteralex** [Swimburger/AzureFunctionsWithTwilioBindings#1]
Hi.

I implemented the code from this [ Send Sms with Twilio and Azure Functions:](https://www.twilio.com/blog/send-sms-with-csharp-dotnet-and-azure-functions-using-the-twilio-output-binding) 

Getting error:

"System.Private.CoreLib: Exception while executing function: SendSmsTimer. SendSmsTimer: Could not load type 'System.Runtime.CompilerServices.DefaultInterpolatedStringHandler' from assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."

My .csproj 

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Twilio" Version="3.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
    <PackageReference Include="Twilio" Version="5.76.0" />
  </ItemGroup>`
  
  I also tried changing the .csproj to match the repo without luck, same error.

**Comment by Swimburger** [comment]
I'm afraid I can't help with that. It sounds like you're running into this issue: https://github.com/Azure/Azure-Functions/issues/2015
Let me know if the suggestions from that issue help.

**Comment by sinisteralex** [comment]
I fixed the error and the function now runs.
It runs on the schedule as per your code.
It does not send SMS too my phone from the Azure Function, so i am not sure how to debug it.

I am able to send SMS from the Twilio-console to my phone.

**Comment by Swimburger** [comment]
There's a couple of things that you could do to debug:
- Check the Error Logs and Messaging. There could be useful information there as why you are not receiving your SMS.
![Screen Shot 2022-07-05 at 2 22 52 PM](https://user-images.githubusercontent.com/3382717/177391533-41938c01-0c1c-45fc-980a-225e6108c185.png)
- If you're on a trial account, make sure your recipient [phone number is on the Verified Caller ID list](https://support.twilio.com/hc/en-us/articles/223180048-Adding-a-Verified-Phone-Number-or-Caller-ID-with-Twilio). 
- Make sure that the phone number that you're trying to text is using the right [format](https://support.twilio.com/hc/en-us/articles/223183008-Formatting-International-Phone-Numbers#h_749baca6-7794-40ed-abb5-ff0dc5782d4e).

**Comment by sinisteralex** [comment]
So after debugging for some more hours i was able to come to the bottom of the problem.
I had the Twilio Nuget-package in my .csproj, after removing it i was able to send SMS without problems without Azure Functions.
